extra-deps: [cond-0.4.1.1]
extra-package-dbs: []
flags: {}
packages:
- {location: .}
- extra-dep: true
  location: {commit: 4f71fdec791731da43ed969053d96c592f205619, git: 'https://github.com/luna/dependent-state.git'}
- extra-dep: true
  location: {commit: 3ba7d5da78aab023fc74c44fc7445ffab0bc18e0, git: 'https://github.com/luna/lens-utils.git'}
- extra-dep: true
  location: {commit: 1451d42c8f9179c6c542e085e9a17ab0b1063206, git: 'https://github.com/luna/prologue.git'}
- extra-dep: true
  location: {commit: 61ff909efd466735cd4820f9ab2c564e324b5546, git: 'https://github.com/luna/container.git'}
- extra-dep: true
  location: {commit: 5d7acbac13a9131c26baa2da27ef6f76f329e019, git: 'https://github.com/luna/convert.git'}
- extra-dep: true
  location: {commit: a6afda3b96efe00938aba61ac12a2f5f2134ff3d, git: 'https://github.com/luna/data-construction.git'}
- extra-dep: true
  location: {commit: 8a5773adba33d71a311ba0b4123b744213b0be91, git: 'https://github.com/luna/data-layer.git'}
- extra-dep: true
  location: {commit: 9da4c9b2534693cfe82adeb37f12eaadacb41e62, git: 'https://github.com/luna/data-repr.git'}
- extra-dep: true
  location: {commit: a1606cccc12cb521acbc598e52c481b9054b42a7, git: 'https://github.com/luna/impossible.git'}
- extra-dep: true
  location: {commit: 1c6a4fd165e4b15cad114b0a554e0974fd119223, git: 'https://github.com/luna/functor-utils.git'}
- extra-dep: true
  location: {commit: c900d8d1d2b63338fdd2d825cb8d2002b8086a20, git: 'https://github.com/luna/typelevel.git'}
- extra-dep: true
  location: {commit: 4f5153aed4944317942ff9025c79f7fc3be85181, git: 'https://github.com/luna/data-rtuple.git'}
- extra-dep: true
  location: {commit: b5f02ced2912501d923c07950789fbcf44a6a9ce, git: 'https://github.com/luna/data-prop.git'}
- extra-dep: true
  location: {commit: 7c7a6d657e7db8c3dcd80fbed0a7e02e02f43ae3, git: 'https://github.com/luna/monad-branch'}
- extra-dep: true
  location: {commit: e63e373d67cd8dd7c179a618f5d32f6ffb3abdd3, git: 'https://github.com/luna/monoid'}
- extra-dep: true
  location: {commit: c75acefee30d1c853da7e651c358d72b60386a07, git: 'https://github.com/luna/layouting'}
- extra-dep: true
  location: {commit: a7f6158465aaa9998fcb094d74906f608ce385c5, git: 'https://github.com/luna/terminal-text'}
resolver: nightly-2017-08-17
